// src/components/file/FileList.tsx
import React from "react";
import {
  Download,
  Trash2,
  Share2,
  File,
  Folder,
  MoreVertical,
} from "lucide-react";
import { Card, CardContent, CardHeader } from "@/components/ui/Card";
import Button from "@/components/ui/Button";
import { formatBytes } from "@/lib/utils";
import type { FileItem } from "@/types";

interface FileListProps {
  files: FileItem[];
  onDownload: (file: FileItem) => void;
  onPreview?: (file: FileItem) => void;
  onShare: (file: FileItem) => void;
  onDelete: (file: FileItem) => void;
}

export default function FileList({
  files,
  onDownload,
  onPreview,
  onShare,
  onDelete,
}: FileListProps) {
  return (
    <Card>
      <CardHeader className="px-4 sm:px-6 py-3 sm:py-4 border-b border-gray-200">
        <h3 className="text-lg font-medium text-gray-900">Pliki</h3>
      </CardHeader>

      {files.length === 0 ? (
        <CardContent className="p-6 sm:p-8 text-center">
          <Folder className="h-10 w-10 sm:h-12 sm:w-12 text-gray-400 mx-auto mb-4" />
          <p className="text-gray-500">Brak plików w tym folderze</p>
        </CardContent>
      ) : (
        <div className="divide-y divide-gray-200">
          {files.map((file) => (
            <FileItem
              key={file.key}
              file={file}
              onDownload={onDownload}
              onPreview={onPreview}
              onShare={onShare}
              onDelete={onDelete}
            />
          ))}
        </div>
      )}
    </Card>
  );
}

interface FileItemProps {
  file: FileItem;
  onDownload: (file: FileItem) => void;
  onPreview?: (file: FileItem) => void;
  onShare: (file: FileItem) => void;
  onDelete: (file: FileItem) => void;
}

function FileItem({
  file,
  onDownload,
  onPreview,
  onShare,
  onDelete,
}: FileItemProps) {
  const [showMobileMenu, setShowMobileMenu] = React.useState(false);

  return (
    <div className="px-4 sm:px-6 py-3 sm:py-4 hover:bg-gray-50 transition-colors">
      {/* Desktop Layout */}
      <div className="hidden sm:flex items-center justify-between">
        <div
          className="flex items-center gap-3 sm:gap-4 cursor-pointer hover:bg-gray-100 rounded-md p-2 -m-2 transition-colors"
          onClick={() => onPreview?.(file)}
        >
          <File className="h-7 w-7 sm:h-8 sm:w-8 text-blue-500" />
          <div className="min-w-0 flex-1">
            <p className="text-sm sm:text-base font-medium text-gray-900 truncate">
              {file.name}
            </p>
            <p className="text-xs sm:text-sm text-gray-500">
              {formatBytes(file.size)} •{" "}
              {new Date(file.lastModified).toLocaleDateString("pl-PL")}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-1 sm:gap-2">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => onDownload(file)}
            className="p-2"
            title="Pobierz"
          >
            <Download className="h-4 w-4" />
          </Button>

          <Button
            variant="ghost"
            size="sm"
            onClick={() => onShare(file)}
            className="p-2"
            title="Udostępnij"
          >
            <Share2 className="h-4 w-4" />
          </Button>

          <Button
            variant="ghost"
            size="sm"
            onClick={() => onDelete(file)}
            className="p-2 text-gray-400 hover:text-red-600"
            title="Usuń"
          >
            <Trash2 className="h-4 w-4" />
          </Button>
        </div>
      </div>

      {/* Mobile Layout */}
      <div className="sm:hidden">
        <div className="flex items-center justify-between">
          <div
            className="flex items-center gap-3 flex-1 min-w-0 cursor-pointer hover:bg-gray-100 rounded-md p-2 -m-2 transition-colors"
            onClick={() => onPreview?.(file)}
          >
            <File className="h-6 w-6 text-blue-500 flex-shrink-0" />
            <div className="min-w-0 flex-1">
              <p className="text-sm font-medium text-gray-900 truncate">
                {file.name}
              </p>
              <p className="text-xs text-gray-500">
                {formatBytes(file.size)} •{" "}
                {new Date(file.lastModified).toLocaleDateString("pl-PL")}
              </p>
            </div>
          </div>

          <Button
            variant="ghost"
            size="sm"
            onClick={() => setShowMobileMenu(!showMobileMenu)}
            className="p-2 ml-2"
          >
            <MoreVertical className="h-4 w-4" />
          </Button>
        </div>

        {/* Mobile Actions Menu */}
        {showMobileMenu && (
          <div className="mt-3 pt-3 border-t border-gray-200">
            <div className="flex gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={() => onDownload(file)}
                className="flex-1"
              >
                <Download className="h-4 w-4 mr-2" />
                Pobierz
              </Button>

              <Button
                variant="outline"
                size="sm"
                onClick={() => onShare(file)}
                className="flex-1"
              >
                <Share2 className="h-4 w-4 mr-2" />
                Udostępnij
              </Button>

              <Button
                variant="outline"
                size="sm"
                onClick={() => onDelete(file)}
                className="flex-1 text-red-600 border-red-200 hover:bg-red-50"
              >
                <Trash2 className="h-4 w-4 mr-2" />
                Usuń
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// src/lib/components/files/FileList.svelte
<script lang="ts">
	import {
		Folder,
		File as FileIcon,
		DotsThreeVertical,
		DownloadSimple,
		Pencil,
		Trash,
		Share
	} from 'phosphor-svelte';
	import { formatFileSize } from '$lib/utils/format';

	type FileType = { $id: string; name: string; size: number; $createdAt: string };
	type FolderType = { $id: string; name: string; $createdAt: string; size?: number };

	let { files, folders, onDownload, onRename, onDelete, onNavigate, onShare } = $props<{
		files: FileType[];
		folders: FolderType[];
		onDownload: (id: string, name: string, isFolder: boolean) => void;
		onRename: (id: string, name: string, isFolder: boolean) => void;
		onDelete: (id: string, name: string, isFolder: boolean) => void;
		onNavigate: (id: string) => void;
		onShare: (id: string, isFolder: boolean) => void;
	}>();

	let activeMenuId = $state<string | null>(null);

	function toggleMenu(id: string) {
		if (activeMenuId === id) activeMenuId = null;
		else activeMenuId = id;
	}
</script>

<div class="space-y-2 lg:hidden">
	<!-- Mobile list with bottom spacing -->
	{#if folders.length === 0 && files.length === 0}
		<div class="py-12 text-center text-text-muted">Folder is empty</div>
	{/if}

	{#each folders as folder (folder.$id)}
		<div class="relative rounded-md border border-border-line bg-bg-panel p-3 shadow-none">
			<div class="flex items-center gap-3">
				<button onclick={() => onNavigate(folder.$id)} class="shrink-0">
					<Folder
						class="h-8 w-8 fill-amber-400 text-amber-600 dark:fill-amber-500/50 dark:text-amber-400"
					/>
				</button>
				<button onclick={() => onNavigate(folder.$id)} class="min-w-0 flex-1 text-left">
					<p class="truncate text-sm font-medium text-text-main">{folder.name}</p>
					<p class="font-mono text-xs text-text-muted">Folder</p>
				</button>
				<button
					onclick={() => toggleMenu(folder.$id)}
					class="rounded-full p-2 text-text-muted hover:bg-gray-100 dark:hover:bg-zinc-800"
				>
					<DotsThreeVertical class="h-5 w-5" />
				</button>
			</div>

			<!-- Context Menu -->
			{#if activeMenuId === folder.$id}
				<div class="mt-3 grid grid-cols-4 gap-2 border-t border-border-line pt-3">
					<button
						onclick={() => {
							onShare(folder.$id, true);
							activeMenuId = null;
						}}
						class="flex flex-col items-center gap-1 rounded-md p-2 hover:bg-gray-50"
					>
						<Share class="h-5 w-5 text-blue-500" />
						<span class="text-[10px] text-text-muted">Udostępnij</span>
					</button>
					<button
						onclick={() => {
							onRename(folder.$id, folder.name, true);
							activeMenuId = null;
						}}
						class="flex flex-col items-center gap-1 rounded-md p-2 hover:bg-gray-50"
					>
						<Pencil class="h-5 w-5 text-text-main" />
						<span class="text-[10px] text-text-muted">Zmień</span>
					</button>
					<button
						onclick={() => {
							onDownload(folder.$id, folder.name, true);
							activeMenuId = null;
						}}
						class="flex flex-col items-center gap-1 rounded-md p-2 hover:bg-gray-50"
					>
						<DownloadSimple class="h-5 w-5 text-primary" />
						<span class="text-[10px] text-text-muted">Pobierz</span>
					</button>
					<button
						onclick={() => {
							onDelete(folder.$id, folder.name, true);
							activeMenuId = null;
						}}
						class="flex flex-col items-center gap-1 rounded-md p-2 hover:bg-red-50"
					>
						<Trash class="h-5 w-5 text-red-600" />
						<span class="text-[10px] text-text-muted">Usuń</span>
					</button>
				</div>
			{/if}
		</div>
	{/each}

	{#each files as file (file.$id)}
		<div class="relative rounded-md border border-border-line bg-bg-panel p-3 shadow-none">
			<div class="flex items-center gap-3">
				<div class="shrink-0">
					<FileIcon class="h-8 w-8 text-blue-500 dark:text-blue-400" />
				</div>
				<div class="min-w-0 flex-1 text-left">
					<p class="truncate text-sm font-medium text-text-main">{file.name}</p>
					<p class="font-mono text-xs text-text-muted">{formatFileSize(file.size)}</p>
				</div>
				<button
					onclick={() => toggleMenu(file.$id)}
					class="rounded-full p-2 text-text-muted hover:bg-gray-100 dark:hover:bg-zinc-800"
				>
					<DotsThreeVertical class="h-5 w-5" />
				</button>
			</div>

			{#if activeMenuId === file.$id}
				<div class="mt-3 grid grid-cols-4 gap-2 border-t border-border-line pt-3">
					<button
						onclick={() => {
							onShare(file.$id, false);
							activeMenuId = null;
						}}
						class="flex flex-col items-center gap-1 rounded-md p-2 hover:bg-gray-50"
					>
						<Share class="h-5 w-5 text-blue-500" />
						<span class="text-[10px] text-text-muted">Udostępnij</span>
					</button>
					<button
						onclick={() => {
							onRename(file.$id, file.name, false);
							activeMenuId = null;
						}}
						class="flex flex-col items-center gap-1 rounded-md p-2 hover:bg-gray-50"
					>
						<Pencil class="h-5 w-5 text-text-main" />
						<span class="text-[10px] text-text-muted">Rename</span>
					</button>
					<button
						onclick={() => {
							onDownload(file.$id, file.name, false);
							activeMenuId = null;
						}}
						class="flex flex-col items-center gap-1 rounded-md p-2 hover:bg-gray-50"
					>
						<DownloadSimple class="h-5 w-5 text-primary" />
						<span class="text-[10px] text-text-muted">Download</span>
					</button>
					<button
						onclick={() => {
							onDelete(file.$id, file.name, false);
							activeMenuId = null;
						}}
						class="flex flex-col items-center gap-1 rounded-md p-2 hover:bg-red-50"
					>
						<Trash class="h-5 w-5 text-red-600" />
						<span class="text-[10px] text-text-muted">Delete</span>
					</button>
				</div>
			{/if}
		</div>
	{/each}
</div>
